url: 'https://sfu-archi.github.io'
baseurl: ''
exclude: ['README.md']
timezone: US/Pacific

permalink: posts/:year-:month-:day-:title

markdown:         kramdown
highlighter:      rouge

permalink:        pretty
